[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirect to index.html since Next.js handles routing differently
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://youbuidl.netlify.app"
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"